# Generated by Django 5.2.1 on 2025-05-31 08:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description for category ')),
            ],
            options={
                'verbose_name': 'Category ',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name product')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='short description for product')),
                ('description', models.TextField(verbose_name='description for product')),
                ('main_price', models.PositiveIntegerField(verbose_name='main price ')),
                ('price_with_discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='price with discount ')),
                ('inventory', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='inventory ')),
                ('image', models.ImageField(blank=True, upload_to='cover/', verbose_name='product image')),
                ('is_special_offer', models.BooleanField(blank=True, default=False, null=True, verbose_name='is special offer')),
                ('ate_time_modified', models.DateTimeField(auto_now=True, verbose_name='date time modified')),
                ('date_time_added', models.DateTimeField(auto_now_add=True, verbose_name='date time added')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'category'], name='store_produ_name_72b6df_idx')],
            },
        ),
    ]
