# Generated by Django 5.2.1 on 2025-05-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_time_added'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
