# Generated by Django 5.2.1 on 2025-05-31 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Color Name')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='weight product')),
                ('size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'very large')], default='L', max_length=3, verbose_name='size')),
                ('colors', models.ManyToManyField(to='store.color', verbose_name='Colors')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='store.product', verbose_name='')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
                'constraints': [models.UniqueConstraint(fields=('product',), name='one_feature_per_product')],
            },
        ),
    ]
