# Generated by Django 5.2.1 on 2025-06-07 07:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'ویژگی ', 'verbose_name_plural': 'ویژگی ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_time_added'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیحات مح.صول'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150, verbose_name='نام '),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ate_time_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه کردن'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال؟'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(blank=True, choices=[('5', '⭐⭐⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('3', '⭐⭐⭐'), ('2', '⭐⭐'), ('1', '⭐')], default=None, max_length=10, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='متن کامنت'),
        ),
        migrations.AlterField(
            model_name='features',
            name='colors',
            field=models.ManyToManyField(to='store.color', verbose_name='رنگ ها'),
        ),
        migrations.AlterField(
            model_name='features',
            name='size',
            field=models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'very large')], default='L', max_length=3, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='features',
            name='weight',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='وزن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ate_time_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category', verbose_name='دسته بندی '),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_time_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه کردن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='cover/', verbose_name='عکس محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='موجودی '),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_special_offer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='پیشنهاد فروش ؟'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_price',
            field=models.PositiveIntegerField(verbose_name='قیمت اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_with_discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیحات کوتاه محصول'),
        ),
    ]
