# Generated by Django 5.2.1 on 2025-05-30 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('code', models.PositiveSmallIntegerField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.DateTimeField(default=datetime.datetime(2025, 5, 30, 10, 23, 33, 643753, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'otp code',
                'verbose_name_plural': 'otp code',
            },
        ),
    ]
