# Generated by Django 5.2.1 on 2025-05-31 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_otpcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 13, 34, 6, 559783, tzinfo=datetime.timezone.utc)),
        ),
    ]
