# Generated by Django 5.2.1 on 2025-05-31 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_otpcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 17, 32, 11, 188379, tzinfo=datetime.timezone.utc)),
        ),
    ]
