# Generated by Django 5.2.1 on 2025-06-01 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_otpcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 1, 16, 53, 50, 135712, tzinfo=datetime.timezone.utc)),
        ),
    ]
