# Generated by Django 5.2.1 on 2025-06-01 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_otpcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 1, 19, 7, 0, 665907, tzinfo=datetime.timezone.utc)),
        ),
    ]
