# Generated by Django 5.2.1 on 2025-06-11 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_otpcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 4, 55, 39, 940234, tzinfo=datetime.timezone.utc)),
        ),
    ]
